security_platform:
  app:
    name: MickeyMouse
    type: web
    login_uri: http://localhost:4200/login/callback
    redirect_uris:
      - http://localhost:4200/login/callback
      - https://ax-ae1-dv-mickey-mouse-wac.azurewebsites.net/login/callback
    post_logout_redirect_uris:
      - http://localhost:4200/logout
      - http://disney.com
  scopes:
    - name: KissMinnie
      description: Allows kissing of Minnie Mouse
    - name: TauntDonald
      description: Allows taunting of Donald Duck
  claims:
    - name: SourceIdArr
      value: user.sourceIdArr
      scopes: ""
      value_type: EXPRESSION
      type: IDENTITY
      always_include: "true"
      group_filter_type: "null"
  policies:
    - name: KissMinnie
      description: Policy who is allowed to kiss Minnie Mouse
      # TODO: See if there's a way to autonum priority based on position in list
      priority: 1
      rules:
        - name: KissMinnie
          priority: 1
          # TODO: Autoformat so only the role name is needed here
          groups: 
            - module.MickeyMouse_group_role_admin.group_id
          scopes: 
            - KissMinnie
    - name: TauntDonald
      description: Policy who is allowed to taunt Donald Duck
      # TODO: See if there's a way to autonum priority based on position in list
      priority: 1
      rules:
        - name: TauntDonald
          priority: 1
          # TODO: Autoformat so only the role name is needed here
          groups: 
            - module.MickeyMouse_group_role_admin.group_id
            - module.MickeyMouse_group_role_manager.group_id
          scopes: 
            - TauntDonald
